services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:kubiat/reverseproxy:v1
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:kubiat/udagram-api-user:v1
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:kubiat/udagram-api-feed:v1
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:kubiat/udagram-frontend:v1