version: 2.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.17.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build using `docker-compose`
          command: |
            docker-compose -f docker-compose-build.yml build
      - run:
          name: Login for Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Push to Docker Hub
          command: |
            docker-compose push
